### ISSUE TITLE
i feel sad

### ISSUE THREAD

**Issue by fad9-TVT** [carl-vbn/opengl-gravity-simulator#2]
The program is too slow , I think it may be caused by my computer being too old. I can only see a circular aperture and 
fuzzy sphere.

**Comment by carl-vbn** [comment]
Huh, that's weird... What hardware are you running on? (CPU & GPU model? amount of RAM?)

**Comment by fad9-TVT** [comment]
> Huh, that's weird... What hardware are you running on? (CPU & GPU model? amount of RAM?)

i5-5200U  8GB AMD Radeon R7 M270

**Comment by carl-vbn** [comment]
Let's try to remove some unessential features to see if they are causing the issue. If you are running the program build, navigate to where the .exe is located. You should have a `shaders` folder. If you are building the program from source, navigate to the root of the project, and you should also have a `shaders` folder there.
Open `shaders/postprocessing/fragmentShader.glsl` in a text editor and replace all its content with this:

```glsl
#version 330 core
out vec4 FragColor;

in vec2 TexCoords;

uniform sampler2D ScreenTexture;
uniform sampler2D EmissionTexture;

void main()
{
    const float gamma = 2.2;
    const float exposure = 1.0;
    vec3 hdrColor = texture(ScreenTexture, TexCoords).rgb;
    vec3 result = vec3(1.0) - exp(-hdrColor * exposure);   
    result = pow(result, vec3(1.0 / gamma));
    FragColor = vec4(result, 1.0);
}
```

and then open `shaders/stars/fragmentShader.glsl` and replace its content with this:

```glsl
#version 330 core

// STAR SPHERE FRAGMENT SHADER

// Interpolated values from the vertex shaders
in vec3 Normal_cameraspace;
in vec2 uv;

// Ouput data
layout(location = 0) out vec3 color;
layout(location = 1) out vec3 emission;

void main() {
    color = vec3(0);
    emission = vec3(0);
}
```

that should get rid of the bloom effect and stars which should speed things up. If this doesn't change anything then the problem is not related to the speed of your GPU and might be a driver issue.

**Comment by fad9-TVT** [comment]
Thanks, the program can run smoothly now, and i can add some function to the modified shader. I am also  interested in computer graphics and machine learning, and I am looking forward to your new program.
